# Generated by Django 5.2.7 on 2025-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyStaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Upload Staff',
                'verbose_name_plural': 'Upload Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DummyStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Upload Students',
                'verbose_name_plural': 'Upload Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload Students',
                'verbose_name_plural': 'Upload Students',
            },
        ),
    ]
