# Generated by Django 6.0.1 on 2026-02-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_attendance_alter_subjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('break_label', models.CharField(blank=True, help_text='Example: Lunch Break, Short Break', max_length=50, null=True)),
            ],
            options={
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='YearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=10)),
                ('section', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('year', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('classroom', models.CharField(blank=True, max_length=20, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.subjectassignment')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.timeslot')),
                ('year_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetables.yearsection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year_section', 'day', 'timeslot', 'semester', 'academic_year'), name='unique_class_timetable'), models.UniqueConstraint(fields=('assignment', 'day', 'timeslot', 'semester', 'academic_year'), name='unique_teacher_timetable'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', False)), fields=('classroom', 'day', 'timeslot', 'semester', 'academic_year'), name='unique_classroom_timetable')],
            },
        ),
    ]
