# Generated by Django 6.0.1 on 2026-02-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_department_staffprofile_branch'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=10)),
                ('classroom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yearsection',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_class_timetable',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_teacher_timetable',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_classroom_timetable',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetables.timeslot'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.staffprofile'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetables.subject'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('subject', 'day', 'timeslot'), name='unique_subject_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('day', 'timeslot', 'subject'), name='unique_teacher_per_timeslot'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='year_section',
        ),
        migrations.DeleteModel(
            name='YearSection',
        ),
    ]
