import { Bot, Calendar, Sparkles, Download } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";
const resources = [{
  label: "Neo AI",
  icon: Bot,
  color: "text-primary",
  bgColor: "bg-primary/10",
  hoverBg: "hover:bg-primary/15",
  href: "/student/chatbot"
}, {
  label: "Timetable",
  icon: Calendar,
  color: "text-success",
  bgColor: "bg-success/10",
  hoverBg: "hover:bg-success/15",
  href: "/timetable"
}, {
  label: "Stress Buster",
  icon: Sparkles,
  color: "text-warning",
  bgColor: "bg-warning/10",
  hoverBg: "hover:bg-warning/15",
  href: "/stress-buster"
}, {
  label: "Download Syllabus",
  icon: Download,
  color: "text-muted-foreground",
  bgColor: "bg-muted",
  hoverBg: "hover:bg-muted/80",
  isDownload: true
}];
export function QuickAccess() {
  const navigate = useNavigate();
  const handleClick = (resource: typeof resources[0]) => {
    if (resource.isDownload) {
      // Create a sample syllabus download
      const syllabusContent = `
NEOCAMPUS - COMPUTER SCIENCE ENGINEERING
SEMESTER 8 SYLLABUS

1. DATA STRUCTURES & ALGORITHMS
   - Arrays, Linked Lists, Stacks, Queues
   - Trees, Graphs, Hashing
   - Sorting & Searching Algorithms
   - Time & Space Complexity Analysis

2. DATABASE MANAGEMENT SYSTEMS
   - ER Diagrams & Normalization
   - SQL & Query Optimization
   - Transaction Management
   - NoSQL Databases

3. COMPUTER NETWORKS
   - OSI & TCP/IP Models
   - Network Protocols
   - Routing Algorithms
   - Network Security

4. OPERATING SYSTEMS
   - Process Management
   - Memory Management
   - File Systems
   - Deadlock Handling

5. WEB TECHNOLOGIES
   - HTML, CSS, JavaScript
   - React & Modern Frameworks
   - Backend Development
   - RESTful APIs

Generated by NeoCampus Academic System
      `;
      const blob = new Blob([syllabusContent], {
        type: 'text/plain'
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'NeoCampus_Syllabus.txt';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else if (resource.href) {
      navigate(resource.href);
    }
  };
  return <div className="stat-card animate-slide-up" style={{
    animationDelay: "0.35s"
  }}>
      <h3 className="text-lg font-semibold text-foreground mb-4">Quick Access</h3>
      
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {resources.map(resource => <button key={resource.label} onClick={() => handleClick(resource)} className={cn("flex flex-col items-center justify-center gap-2 p-4 rounded-xl transition-all duration-200 group", resource.bgColor, resource.hoverBg)}>
            <div className={cn("w-12 h-12 rounded-xl flex items-center justify-center bg-card shadow-sm transition-transform group-hover:scale-105")}>
              <resource.icon className={cn("w-6 h-6", resource.color)} />
            </div>
            <p className="text-sm font-medium text-foreground text-center">{resource.label}</p>
          </button>)}
      </div>
    </div>;
}