# Generated by Django 5.2.7 on 2025-11-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('lecture_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plan', to='attendance.subjectassignment')),
            ],
            options={
                'ordering': ['lecture_number'],
                'unique_together': {('assignment', 'lecture_number')},
            },
        ),
    ]
