# Generated by Django 5.2.7 on 2025-11-18 17:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teachingplan'),
        ('profiles', '0006_rename_department_staffprofile_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('marked_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='assignment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('subject', 'batch_id', 'semester')},
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['subject', 'batch_id', 'semester'], name='attendance__subject_61fb68_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['assignment_id'], name='attendance__assignm_ef6be6_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['staff'], name='attendance__staff_i_2f9f35_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingplan',
            index=models.Index(fields=['assignment'], name='attendance__assignm_12587f_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingplan',
            index=models.Index(fields=['lecture_number'], name='attendance__lecture_30e601_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teaching_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.teachingplan'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teaching_plan'], name='attendance__teachin_29c9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance__student_018d17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('teaching_plan', 'student')},
        ),
    ]
