# Generated by Django 6.0.1 on 2026-02-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='chunk',
            name='chunk_index',
            field=models.PositiveIntegerField(help_text='Order of chunk inside the document'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='context',
            field=models.CharField(help_text='Subject / topic this chunk is about', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='context',
            field=models.CharField(help_text='Subject / topic / title of the document', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_id',
            field=models.CharField(help_text='System or externally generated file ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
