# Generated by Django 6.0.1 on 2026-02-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chunk_options_alter_uploadeddocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Optional. Leave empty for manually added chunks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='chatbot.uploadeddocument'),
        ),
    ]
