# Generated by Django 6.0.1 on 2026-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chunk_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=models.BinaryField(blank=True, help_text='Sentence-transformer embedding (pickled vector)', null=True),
        ),
    ]
