"""
Django settings for neocampus project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path

# Load environment variables FIRST
from dotenv import load_dotenv
load_dotenv()

# THEN import decouple
from decouple import config
from datetime import timedelta

#For deployement
import os
import dj_database_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="").split(",") #for deployment commented out
ALLOWED_HOSTS = ["*"]


INTERNAL_IPS = [
    "127.0.0.1","localhost",
] # For Django Debug Toolbar - Sarang


# Application definition

INSTALLED_APPS = [
    "jazzmin", # Jazzmin for Admin UI Customization - Sarang
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "results", #-sarang
    'accounts', #-sarang
    'attendance', #-sarang
    'profiles', #-sarang
    'home', #-sarang
    'resultanalysis', #-sarang
    'timetables', #-sarang
    'noticeboard', #-sarang
    "chatbot.apps.ChatbotConfig", #chatbot app config to register signals -sarang
    "rest_framework", #-ReaactJS
    "corsheaders", #-ReaactJS
    "debug_toolbar", # Django Debug Toolbar for API Trakcing - Sarang
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware', #for deployment
    # 'whitenoise.middleware.WhiteNoiseMiddleware', #for deployment
    "corsheaders.middleware.CorsMiddleware", #-ReaactJS
    "debug_toolbar.middleware.DebugToolbarMiddleware", # Django Debug Toolbar for API Trakcing - Sarang
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'neocampus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'neocampus.wsgi.application'


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
} #for local system

# DATABASES = {
#     "default": dj_database_url.config(default=os.environ.get("DATABASE_URL"))
# } #for deployment


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#manually added -Sarang

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# auth redirects
LOGIN_URL = '/admin/'                       # where @login_required redirects
LOGIN_REDIRECT_URL = '/dashboard/'          # after successful login
LOGOUT_REDIRECT_URL = '/admin/'                   # after logout



CORS_ALLOW_ALL_ORIGINS = True

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}



#--------------------------------------------
# Django Jaszmin Admin Customization Settings
#---------------------------------------------
# ADMIN_SITE_TITLE = "NeoCampus Admin"
# ADMIN_SITE_HEADER = "NeoCampus Admin"

JAZZMIN_SETTINGS = {
    

    "site_title": "NeoCampus",
    "site_header": "NeoCampus Admin -B",
    "site_brand": "NeoCampus Admin",

    "site_logo": "images/favicon.svg",
    "site_icon": "images/favicon.svg",
    "site_logo_classes": "img-circle elevation-3",
    

    "welcome_sign": "Welcome to NeoCampus Admin Panel",

    "show_sidebar": True,
    "navigation_expanded": True,
    "sidebar_fixed": True,
    "navbar_fixed": True,
    "footer_fixed": True,
    "navigation_expanded": True,
    "theme": "lux",

    "sidebar": {
        "show_search": True,
        "show_all_applications": True,
    },

    "show_ui_builder": False,

    "order_with_respect_to": [
        "accounts",
        "profiles",
        "attendance",
        "results",
        "resultanalysis",
        "timetables",
        "noticeboard",
        "chatbot",
    ],

    "icons": {
        "accounts": "fas fa-user",
        "profiles": "fas fa-id-card",
        "attendance": "fas fa-calendar-check",
        "results": "fas fa-poll",
        "resultanalysis": "fas fa-chart-line",
        "timetables": "fas fa-clock",
        "noticeboard": "fas fa-bullhorn",
        "chatbot": "fas fa-robot",
        "auth": "fas fa-users-cog",
    },

    "custom_links": {
        "accounts": [{
            "name": "Manage Users",
            "url": "admin:accounts_user_changelist",
            "icon": "fas fa-users",
            "permissions": ["accounts.view_user"]
        }],
    },
}