# Generated by Django 6.0.1 on 2026-02-27 16:53

import django.db.models.deletion
import django.utils.timezone
import noticeboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brief_message', models.TextField()),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notice_files/', validators=[noticeboard.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='noticeboard.notice')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='noticeboard.notice')),
            ],
        ),
    ]
