# Generated by Django 5.2.7 on 2025-11-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_staffprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
