# Generated by Django 5.2.7 on 2025-11-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_staffprofile_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
