# Generated by Django 5.2.7 on 2025-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_studentprofile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
