# Generated by Django 5.2.7 on 2025-11-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_staffprofile_is_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='department',
            new_name='branch',
        ),
    ]
