# Generated by Django 6.0.1 on 2026-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='roll',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='roll',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
