# Generated by Django 6.0.1 on 2026-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_roll_staffprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='hardware_public_key',
            field=models.TextField(blank=True, help_text="User's hardware public key for signature login", null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hardware_public_key',
            field=models.TextField(blank=True, help_text="User's hardware public key for signature login", null=True),
        ),
    ]
